apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.name }}-secret
  labels:
    app: {{ .Values.postgresql.name }}
type: Opaque
stringData:
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database | quote }}
  POSTGRESQL_USER: {{ .Values.postgresql.username | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | quote }}